name: youtube_player_iframe_web
description: Web implementation of webview_flutter plugin tailored for using with youtube_player_iframe package.
version: 3.1.1
homepage: https://github.com/sarbagyastha/youtube_player_flutter/tree/main/packages/youtube_player_iframe_web

environment:
  sdk: ">=3.3.0 <3.6.0"

flutter:
  plugin:
    implements: youtube_player_iframe
    platforms:
      web:
        pluginClass: WebYoutubePlayerIframePlatform
        fileName: src/web_youtube_player_iframe_platform.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  webview_flutter_platform_interface: ^2.10.0

dev_dependencies:
  flutter_lints: ^5.0.0
